# -*- coding: utf-8 -*-
"""Python.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16QyI0cBiFLnnpnGchX8IWR37VYdRMqnM

# Python

1. Explain the key features of Python that make it a popular choice for programming.

-> Python is popular because of its simplicity, versatility, and large community support.

**Main Features:**

Easy to Learn and Read – Syntax is close to English.

- Example: print("Hello, World!")


Interpreted Language – No need to compile; code runs line by line.

Cross-platform – Works on Windows, macOS, Linux without changes.

Extensive Libraries – Has built-in and third-party modules.

Versatile – Used in web dev, data science, AI, automation, etc.

Dynamic Typing – No need to declare variable types explicitly.

2. Describe the role of predefined keywords in Python and provide examples of how they are used in a program.

-> In Python, keywords are special reserved words that hold predefined meanings and purposes. These words form the basic building blocks of Python syntax and cannot be used as variable names, function names, or identifiers, as doing so would cause a syntax error. Python keywords are all in lowercase (except True, False, and None) and are used to define the structure and flow of programs.

Keywords help Python understand what operations to perform; for instance, if, else, and elif are used for conditional statements, for and while for looping, and def for defining functions. Without keywords, it would be impossible to write meaningful Python programs, as they define how statements are interpreted by the Python interpreter.
"""

if True:
    print("Condition is True")

for i in range(3):
    print(i)

"""3. Compare and contrast mutable and immutable objects in Python with examples.

-> In Python, mutability refers to whether an object’s value can be changed after creation.

- Mutable objects can be modified after they are created. Lists, dictionaries, and sets fall into this category.

- Immutable objects cannot be changed after creation. Examples include strings, tuples, and integers.

When you change a mutable object, the same memory location is updated. However, when you attempt to change an immutable object, Python creates a new object in memory with the updated value, leaving the original unchanged. Understanding this concept is crucial for writing efficient and bug-free programs, especially when passing objects as function arguments.
"""

# Mutable example
my_list = [1, 2, 3]
my_list.append(4)  # Modifies existing list
print(my_list)  # [1, 2, 3, 4]

# Immutable example
name = "Aman"
name = "Singh"  # Creates a new string
print(name)  # Singh

"""4. Discuss the different types of operators in Python and provide examples of how they are used.

-> Operators in Python are special symbols that perform operations on variables and values.

They can be classified as:

- Arithmetic Operators – Perform mathematical operations: +, -, *, /, %, **, //.

- Relational/Comparison Operators – Compare values: ==, !=, >, <, >=, <=.

- Logical Operators – Combine conditional statements: and, or, not.

- Assignment Operators – Assign values: =, +=, -=, *=, /=.

- Bitwise Operators – Operate on binary data: &, |, ^, ~, <<, >>.

- Membership Operators – Test membership: in, not in.

- Identity Operators – Compare object memory locations: is, is not.
"""

a = 10
b = 5

# Arithmetic
print(a + b)  # 15

# Comparison
print(a > b)  # True

# Logical
print(a > 0 and b > 0)  # True

# Membership
print(2 in [1, 2, 3])  # True

"""5. Explain the concept of type casting in Python with examples.

-> Type casting refers to converting a variable from one data type to another.

Python supports two types of type casting:

- Implicit Type Casting: Automatically performed by Python when safe (e.g., int to float).

- Explicit Type Casting: Manually performed using functions like int(), float(), str().

Type casting is useful when performing operations between incompatible data types, such as concatenating numbers and strings or performing arithmetic on numeric strings.
"""

# Implicit casting
x = 5
y = 2.5
result = x + y  # int converted to float automatically
print(result)  # 7.5

# Explicit casting
num_str = "10"
num_int = int(num_str)
print(num_int + 5)  # 15

"""6. How do conditional statements work in Python? Illustrate with examples.

-> Conditional statements allow programs to make decisions based on certain conditions.

Python uses if, elif, and else to control the flow of execution.

- if: Executes a block if the condition is True.

- elif: Executes if the previous if condition is False and its own condition is True.

- else: Executes if all previous conditions are False.

They are fundamental for implementing decision-making logic in programs.
"""

age = 18
if age >= 18:
    print("You are an adult")
elif age > 13:
    print("Teenager")
else:
    print("Child")

"""7. Describe the different types of loops in Python and their use cases with examples.

-> Loops are used to execute a block of code repeatedly until a condition is met.

Python has:

- For Loop – Iterates over a sequence such as a list, tuple, or string.

- While Loop – Runs as long as a condition is true.

- Nested Loops – A loop inside another loop for complex iterations.

Loop control statements like break, continue, and pass allow finer control over loop execution.
"""

# For loop
for i in range(5):
    print(i)

# While loop
x = 0
while x < 3:
    print(x)
    x += 1

# Using break
for num in range(10):
    if num == 5:
        break
    print(num)